### ISSUE TITLE
Compilation errors with gcc 13.2.1, easy fix

### ISSUE THREAD

**Issue by csalvaggio** [alandefreitas/matplotplusplus#386]
**Bug category**

- [x] *bug - compilation error*
- [ ] *bug - compilation warning*
- [ ] *bug - runtime error*
- [ ] *bug - runtime warning*
- [ ] *bug - logic error*

**Describe the bug**
When compiling with gcc 13.2.1 on Fedora, the use of the integer typedefs causes errors in the colors.cpp file.

Easy fix is to add

```#include <cstdint>```

to that file.

**Environment Details:**
 - OS: Fedora
 - OS Version: 38
 - Compiler: g++
 - Compiler version: 13.2.1

**Comment by Omelug** [comment]
Already fixed in #341 
 Had same issue with matplot v1.1.0, gcc version 15.2.0 (Debian 15.2.0-12), works on matplot v1.2.2

**Comment by alandefreitas** [comment]
Can we close this one then?
